### ISSUE TITLE
Mind publishing the latest to NPM?

### ISSUE THREAD

**Issue by trusktr** [dvlsg/async-csp#12]
My project uses Babel 6, so it wouldn't work with async-csp `0.3.0` from NPM, so for now I'm using async-csp from GitHub which is working fine.

https://github.com/meteor/meteor/issues/6597

**Comment by dvlsg** [comment]
Absolutely -- it sounds like there's a potential version issue, then, so I'm probably going to bump it all the way up to `0.4.0`. Should really get it all the way to `1.0.0` and start following proper semver. Some day soon.

**Comment by dvlsg** [comment]
Alright, `0.4.0` is out in the wild on both `npm` and github. Holler if it gives you any problems. Mine was actually being a bit of a pain, but I think it was just me wrestling with `npm` (hopefully). Once I got it to actually build and stop throwing permissions errors from `babel` packages, all the unit tests stayed passing.
