### ISSUE TITLE
Default size to zero.

### ISSUE THREAD

**Issue by trusktr** [dvlsg/async-csp#2]
Opening this thread separately, regarding https://github.com/dvlsg/async-csp/issues/1#issuecomment-154479943.

If we set the Channel.DEFAULT_SIZE to zero, it doesn't seem like it'll work at all right now because the queue can never be empty, which the code relies on at the moment? Seems like the FixedQueue structure could be used for when size >= 1, but a separate mechanism for when size is zero?

**Comment by dvlsg** [comment]
Hm. One question for you first: in the following code, how would you expect this to work (or not work) when default size is zero (assume execution is in an async context):

```js
let ch = new Channel();
await ch.put(1);
let val = await ch.take();
```

Would you expect the `ch.take()` to never execute, since `ch.put()` would block until a take is executed?

**Comment by dvlsg** [comment]
After poking around with the code for a while, I feel that the best way to accomplish that functionality would be to work on a refactor which would allow buffer-less channels.

Right now, `slide()` is looking to see space on the buffer is available before resolving the `put`, but in order to accomplish blocking on the first `put`, the logic would need to wait until at least one `take` is available instead -- but only when a buffer is being used.

**Comment by trusktr** [comment]
> ```js
> let ch = new Channel();
> await ch.put(1);
> let val = await ch.take();
> ```

In that case it just wouldn't work. The reference to `ch` would have to be created outside of the function, and another process would have to call `ch.take()` on it in order to make this process resume, and then this process would pause at `let val = await ch.take()` until another process calls `ch.put`.

Let's make sure the docs mention that this won't be possible. :+1:

**Comment by dvlsg** [comment]
I just pushed the refactor to the develop branch, if you were interested in taking a look. There is still lots to do (performance, tests, docs, examples, etc), but the functionality should all be there, with non-buffered channels as the new default.

**Comment by dvlsg** [comment]
Landed in [v0.3.0](https://github.com/dvlsg/async-csp/releases/tag/v0.3.0).

**Comment by trusktr** [comment]
Looks awesome!! Thanks for the update. This is one of my new favorite libs right now. :smiley:

**Comment by dvlsg** [comment]
No problem! It was a good suggestion. And I'm glad someone other than myself has a use for the code. :+1:
